server:
  port: 8080
spring:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    api-docs:
      path: /v3/api-docs
    group-configs:
      group: 'nigra-testudo'
      paths-to-match: '/**'
      packages-to-scan: me.jet.ocr
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
  application:
    name: nigra-testudo-app
  shardingsphere:
    mode:
      type: Standalone
      repository:
        type: JDBC
        path: shardingsphere
    datasource:
      common:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: org.postgresql.Driver
      names: nigra1,nigra2,nigra3,nigra4
      nigra1:
        driver-class-name: org.postgresql.Driver
        jdbc-url: jdbc:postgresql://localhost:5432/nigra1
        username: postgres
        password:
        type: com.zaxxer.hikari.HikariDataSource
        hikari:
          minimum-idle: 5
          maximum-pool-size: 10
          idle-timeout: 30000
          connection-timeout: 30000
          max-lifetime: 600000
      nigra2:
        driver-class-name: org.postgresql.Driver
        jdbc-url: jdbc:postgresql://localhost:5432/nigra2
        username: postgres
        password:
        type: com.zaxxer.hikari.HikariDataSource
        hikari:
          minimum-idle: 5
          maximum-pool-size: 10
          idle-timeout: 30000
          connection-timeout: 30000
          max-lifetime: 600000
      nigra3:
        driver-class-name: org.postgresql.Driver
        jdbc-url: jdbc:postgresql://localhost:5432/nigra3
        username: postgres
        password:
        type: com.zaxxer.hikari.HikariDataSource
        hikari:
          minimum-idle: 5
          maximum-pool-size: 10
          idle-timeout: 30000
          connection-timeout: 30000
          max-lifetime: 600000
      nigra4:
        driver-class-name: org.postgresql.Driver
        jdbc-url: jdbc:postgresql://localhost:5432/nigra4
        username: postgres
        password:
        type: com.zaxxer.hikari.HikariDataSource
        hikari:
          minimum-idle: 5
          maximum-pool-size: 10
          idle-timeout: 30000
          connection-timeout: 30000
          max-lifetime: 600000
    props:
      sql-show: true
    rules:
      sql-parser:
        sql-comment-parse-enabled: true
      sql-statement-cache:
        maximum-size: 65535
        initial-capacity: 2000
      parse-tree:
        initial-capacity: 128
        maximum-size: 1024
      sharding:
        tables:
          tb_user:
            actual-data-nodes: nigra${1..4}.tb_user_${0001..0004}
            database-strategy:
              standard:
                sharding-column: sharding_val
                sharding-algorithm-name: ds-inline
            table-strategy:
              standard:
                sharding-column: sharding_val
                sharding-algorithm-name: tb-inline
        sharding-algorithms:
          ds-inline:
            type: CLASS_BASED
            props:
              strategy: STANDARD
              algorithmClassName: me.jet.ocr.strategy.CustomDSShardingAlgorithm
          tb-inline:
            type: CLASS_BASED
            props:
              strategy: STANDARD
              algorithmClassName: me.jet.ocr.strategy.CustomTBShardingAlgorithm
        default-sharding-column: sharding_val
        default-table-strategy:
          standard:
            sharding-column: sharding_val
            sharding-algorithm-name: tb-inline
        default-database-strategy:
          standard:
            sharding-column: sharding_val
            sharding-algorithm-name: ds-inline

knife4j:
  enable: true
  setting:
    language: zh_cn
mybatis-plus:
  type-aliases-package: me.jet.orc.entity
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    logic-delete-field: record_st_cd
    logic-delete-value: 1
    logic-not-delete-value: 0
    db-config:
      id-type: auto
pagehelper:
  helper-dialect: postgresql
  reasonable: true
  support-methods-arguments: true


logging:
  level:
    root: DEBUG
    org.apache.shardingsphere: DEBUG
    org.springframework: DEBUG
    me: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: application.log
    path: ./logs
    max-size: 10MB
    max-history: 30
