server:
  port: 8080
spring:
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
  application:
    name: nigra-testudo-app
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/nigra1?useUnicode=true&characterEncoding=utf-8
    username: postgres
    password:
  shardingsphere:
    datasource:
      common:
        driver-class-name: org.postgresql.Driver
      names: ds0, ds1
      ds1: #数据源1
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: org.postgresql.Driver
        jdbc-url: jdbc:postgresql://127.0.0.1:5432/nigra1?useUnicode=true&characterEncoding=utf-8
        username: postgres
        password:
      ds2: #数据源2
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: org.postgresql.Driver
        jdbc-url: jdbc:postgresql://127.0.0.1:5432/nigra2?useUnicode=true&characterEncoding=utf-8
        username: postgres
        password:
      ds3: #数据源3
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: org.postgresql.Driver
        jdbc-url: jdbc:postgresql://127.0.0.1:5432/nigra3?useUnicode=true&characterEncoding=utf-8
        username: postgres
        password:
      ds4: #数据源4
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: org.postgresql.Driver
        jdbc-url: jdbc:postgresql://127.0.0.1:5432/nigra4?useUnicode=true&characterEncoding=utf-8
        username: postgres
        password:
    rules:
      sharding:
        default-database-strategy:
          standard:
            sharding-column: sharding_val
            sharding-algorithm-name: ds-algorithm
        default-table-strategy:
          standard:
            sharding-column: sharding_val
            sharding-algorithm-name: tb-algorithm
        sharding-algorithms:
          ds-algorithm:
            type: CLASS_BASED
            props:
              strategyClassName: me.jet.ocr.strategy.CustomDSShardingAlgorithm
          tb-algorithm:
            type: CLASS_BASED
            props:
              strategyClassName: me.jet.ocr.strategy.CustomTBShardingAlgorithm

  main:
    allow-bean-definition-overriding: true
  mybatis:
    type-aliases-package: me.jet.orc.entity
    mapper-locations: classpath*:/mapper/**/*.xml


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    logic-delete-field: deleted
    logic-delete-value: 1
    logic-not-delete-value: 0
    db-config:
      table_prefix: tb_
      id-type: auto
pagehelper:
  helper-dialect: postgresql
  reasonable: true
  support-methods-arguments: true


