server:
  port: 8080
spring:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    api-docs:
      path: /v3/api-docs
    group-configs:
      - group: 'nigra-testudo'
        paths-to-match: '/**'
        packages-to-scan: me.jet.ocr
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
  application:
    name: nigra-testudo-app
  shardingsphere:
    mode:
      type: Standalone
      repository:
        type: JDBC
    database: nigra1
    datasource:
      common:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: org.postgresql.Driver
      names: ds0,ds1,ds2,ds3
      ds0:
        driver-class-name: org.postgresql.Driver
        jdbc-url: jdbc:postgresql://localhost:5432/nigra1
        username: postgres
        password:
        type: com.zaxxer.hikari.HikariDataSource
        hikari:
          minimum-idle: 5
          maximum-pool-size: 10
          idle-timeout: 30000
          connection-timeout: 30000
          max-lifetime: 600000
      ds1:
        driver-class-name: org.postgresql.Driver
        jdbc-url: jdbc:postgresql://localhost:5432/nigra2
        username: postgres
        password:
        type: com.zaxxer.hikari.HikariDataSource
        hikari:
          minimum-idle: 5
          maximum-pool-size: 10
          idle-timeout: 30000
          connection-timeout: 30000
          max-lifetime: 600000
      ds2:
        driver-class-name: org.postgresql.Driver
        jdbc-url: jdbc:postgresql://localhost:5432/nigra3
        username: postgres
        password:
        type: com.zaxxer.hikari.HikariDataSource
        hikari:
          minimum-idle: 5
          maximum-pool-size: 10
          idle-timeout: 30000
          connection-timeout: 30000
          max-lifetime: 600000
      ds3:
        driver-class-name: org.postgresql.Driver
        jdbc-url: jdbc:postgresql://localhost:5432/nigra4
        username: postgres
        password:
        type: com.zaxxer.hikari.HikariDataSource
        hikari:
          minimum-idle: 5
          maximum-pool-size: 10
          idle-timeout: 30000
          connection-timeout: 30000
          max-lifetime: 600000
    props:
      sql-show: true
    rules:
      sharding:
        default-database-strategy:
          standard:
            sharding-column: sharding_val
            sharding-algorithm-name: ds-inline
        default-table-strategy:
          standard:
            sharding-column: sharding_val
            sharding-algorithm-name: tb-inline
        sharding-algorithms:
          ds-inline:
            type: CLASS_BASED
            props:
              strategy: STANDARD
              algorithmClassName: me.jet.ocr.strategy.CustomDSShardingAlgorithm
          tb-inline:
            type: CLASS_BASED
            props:
              strategy: STANDARD
              algorithmClassName: me.jet.ocr.strategy.CustomTBShardingAlgorithm
knife4j:
  enable: true
  setting:
    language: zh_cn
mybatis-plus:
  type-aliases-package: me.jet.orc.entity
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    logic-delete-field: record_st_cd
    logic-delete-value: 1
    logic-not-delete-value: 0
    db-config:
      table_prefix: tb_
      id-type: auto
pagehelper:
  helper-dialect: postgresql
  reasonable: true
  support-methods-arguments: true
#
#datasource:
#  names: ds1,ds2,ds3,ds4
#  ds1: #数据源1
#    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
#    driverClassName: org.postgresql.Driver
#    jdbcUrl: jdbc:postgresql://127.0.0.1:5432/nigra1?useUnicode=true&characterEncoding=utf-8
#    username: postgres
#    password:
#  ds2: #数据源2
#    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
#    driverClassName: org.postgresql.Driver
#    jdbcUrl: jdbc:postgresql://127.0.0.1:5432/nigra2?useUnicode=true&characterEncoding=utf-8
#    username: postgres
#    password:
#  ds3: #数据源3
#    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
#    driverClassName: org.postgresql.Driver
#    jdbcUrl: jdbc:postgresql://127.0.0.1:5432/nigra3?useUnicode=true&characterEncoding=utf-8
#    username: postgres
#    password:
#  ds4: #数据源4
#    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
#    driverClassName: org.postgresql.Driver
#    jdbcUrl: jdbc:postgresql://127.0.0.1:5432/nigra4?useUnicode=true&characterEncoding=utf-8
#    username: postgres
#    password:
#  props:
#    sql-show: true
#  rules:
#    defaultShardingColumn: sharding_val
#    defaultDatabaseStrategy:
#      standard:
#        shardingColumn: sharding_val
#        shardingAlgorithmName: ds-inline
#    defaultTableStrategy:
#    shardingAlgorithms:
#      ds-inline:
#        type: CLASS_BASED
#        props:
#          strategy: me.jet.ocr.strategy.CustomDSShardingAlgorithm
#      tb-inline:
#        type: CLASS_BASED
#        props:
#          strategy: me.jet.ocr.strategy.CustomTBShardingAlgorithm


